### ISSUE TITLE
Tailwind Theming 

### ISSUE THREAD

**Issue by kyle-ce** [kyle-ce/ui-dashboard#1]
# Description
Currently hardcoding teal theme color in code

## TODO
- [x] - Follow best practices for updating tailwind theming config 
- [x] - add theming config to project / replace code necessary for themes 
- [x] - add react context to toggle between light and dark
